# Site settings
baseurl = "https://www.kenjisato.jp/"
themesDir = "themes"
publishDir = "public"
title = "kenjisato.jp"
theme = "hugo-theme-cactus-plus"
defaultContentLanguage = "ja"
hasCJKLanguage = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-8443903-1"

# Disable comments by leaving disqusShortname empty
disqusShortname = "kenjisatojp"
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
post = "/post/:year/:month/:slug/"

# Site parameters
[params]
	name = "Kenji Sato"
	description = "a little page"
	bio = "economics and programing"
	# Enter optionally your twitter account
	twitter = "kenjisatojp"
	enableRSS = true
	enableSummary = true
	enableGoogleAnalytics = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/highlight.css", "css/mystyle.css"]
	customJS  = ["js/highlight.js"]

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "Research"
	privacyLink = "privacy"
	# subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Loves Economics, Programming and Beer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

# Add additional social link entries underneath
[social]
  twitter  = "https://www.twitter.com/kenjisatojp"
  facebook = "https://www.facebook.com/kenjisato.jp"
  githubalt   = "https://www.github.com/kenjisato"
  # googleplus  = "https://plus.google.com/+KenjiSato198"
  email = "mailto:mail@kenjisato.jp"


# Translation

[Languages]
[Languages.ja]
weight = 0
languageName = "日本語"
languageCode = "ja-jp"
[Languages.en]
weight = 10
languageName = "English"
languageCode = "en-us"

# MARKUP

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
