---
title: "Macroeconomics (2017Q2)"
slug: "ma/2017q2"
---

# 2017 Q2 Macroeconomics (Kobe Univ.)

## Course materials

- Day 01
    - [Slides](https://cdn.rawgit.com/rokko-ma17q2/slides/9c6d2de2/day01/day01.html)
    - [Syllabus : A](https://cdn.rawgit.com/rokko-ma17q2/slides/9c6d2de2/handouts/ma17q2-A.pdf)
    - [Problem Set : B](https://cdn.rawgit.com/rokko-ma17q2/slides/9c6d2de2/handouts/ma17q2-B.pdf)
    - [Homework : hw01](https://rawgit.com/rokko-ma17q2/hw01/master/problem.pdf)
- Day 02
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day02/day02.html)
    - [Problem Set : C](https://cdn.rawgit.com/rokko-ma17q2/slides/18d08796/handouts/ma17q2-C.pdf)
    - [Homework : hw02](https://rawgit.com/rokko-ma17q2/hw02/master/problem.pdf)
    - Exercise : ex01
- Day 03
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day03/day03.html)
    - [Problem Set : D](https://cdn.rawgit.com/rokko-ma17q2/slides/57b986a9/handouts/ma17q2-D.pdf)
    - [Exercise : ex02](https://rawgit.com/rokko-ma17q2/ex02/master/problem.pdf)
- Day 04
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day04/day04.html)
    - [Problem Set : E](https://cdn.rawgit.com/rokko-ma17q2/slides/5940815d/handouts/ma17q2-E.pdf)
    - [Exercise : ex03](https://rawgit.com/rokko-ma17q2/ex03/master/problem.pdf)
- Day 05
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day05/day05.html)
    - [Problem Set : F](https://cdn.rawgit.com/rokko-ma17q2/slides/083f938d/handouts/ma17q2-F.pdf)
    - [Homework : hw03](https://cdn.rawgit.com/rokko-ma17q2/hw03/acb91098/problem.pdf)
- Day 06
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day06/day06.html)
    - [Problem Set : G](https://cdn.rawgit.com/rokko-ma17q2/slides/84ff5356/handouts/ma17q2-G.pdf)
    - [Midterm : Due on 2017/07/14 18:00](https://rawgit.com/rokko-ma17q2/mid/master/problem.pdf)
- Day 07
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day07/day07.html)
    - [Problem Set : H](https://cdn.rawgit.com/rokko-ma17q2/slides/0d62501a/handouts/ma17q2-H.pdf)
- Day 08
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day08/day08.html)
    - [Problem Set : I](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-I.pdf)
- Day 09
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day09/day09.html)
    - [Problem Set : J](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-J.pdf)
- Day 10
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day10/day10.html)
    - [Problem Set : K](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-K.pdf)
- Day 11
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day11/day11.html)
    - [Problem Set : L](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-L.pdf)
- Day 12
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day12/day12.html)
    - [Problem Set : M](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-M.pdf)
- Day 13
    - [Slides](https://rawgit.com/rokko-ma17q2/slides/master/day13/day13.html)
    - [Problem Set : N](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-N.pdf)
    - [Problem Set : O](https://rawgit.com/rokko-ma17q2/slides/master/handouts/ma17q2-O.pdf)


## Assignments and exercises

See https://github.com/rokko-ma17q2/hw-portal

Assignments should be submitted through GitHub unless otherwise stated.
Always start an assignment from the "Get Invitation" link in the above portal site.

## Additional Information

If you plan to use at a computer at the computer lab, you might want to 
know several techniques to install applications on Mac. See [hw-portal/Wiki](https://github.com/rokko-ma17q2/hw-portal/wiki)


Here is a series of notes concerning R, R Markdown and related stuff.

* [Quick Tutorial for R Markdown](https://cdn.rawgit.com/kenjisato/tips/2e4d7a9d/rmarkdown-basic/basic.html)

